### ISSUE TITLE
_isnan(x) not declared

### ISSUE THREAD

**Issue by clement-moulin-frier** [jschn/TPC#1]
Hi Jan,

I'm currently adapting your code to run it under linux and it works well (I can send you a pull request if you want).

However, I had to remove this line in izhikevich_neuron.h

```
 #define isnan(x) _isnan(x)
```

because it causes this error at compilation:

```
error: ‘_isnan’ was not declared in this scope
```

Do you think it's OK to use the usual isnan without the underscore or did you add this definition for a particular aim?

Thanks,
Clément

**Comment by jschn** [comment]
Hello Clément,

first of all, I'm terribly sorry, that you have to deal with my messy code now! :)
I will do my best to support you wherever possible.
Initially, the aim was to make the code platform independent (therefore the use of Cmake), but in the end I had lots of loose ends and time was running out.

Actually, the line you mentioned only exists because I wrote most of the code on a linux platform and later had to use a windows machine and the compiler complained about the isnan() function.
So it was only a quick fix and it's perfectly fine to delete that line.

Yes, send the pull request, if you like. I'm interested in your changes.
As I still want to publish something on that project, I might restructer the code a bit on my own, too.

Best regards,

Jan

**Comment by clement-moulin-frier** [comment]
Thank you for you quick reply Jan, I replied by email, please let me know if you have not received it (not sure I've the good address).
